version: '3.3'
services:
  gammu-backend:
    image: leandr/sms-gateway:latest
    restart: always
    ports:
      - ${EXPOSED_PORT}:8000
    depends_on:
      - "gammu-db"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_IP=${SERVER_IP}
      - API_SECURITY=${API_SECURITY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - GAMMU_SMSD_CONF=${GAMMU_SMSD_CONF}
      - GAMMU_DEVICE=${GAMMU_DEVICE}
      - GAMMU_DEVICE_CONNECTION=${GAMMU_DEVICE_CONNECTION}
      - GAMMU_PIN=${GAMMU_PIN}
      - GAMMU_DEBUG_LEVEL=${GAMMU_DEBUG_LEVEL}
      - START_GAMMU=${START_GAMMU}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - API_PREFIX=${API_PREFIX}
  gammu-db:
    image: webhippie/mariadb
    restart: always
    volumes:
      - gammu_mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MARIADB_USER=${MYSQL_USERNAME}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}

volumes:
  gammu_mysql:
